name: Upbit Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # [수정] 캐시할 파일 목록에 .first_run_complete 추가
    - name: Restore cache
      uses: actions/cache@v4
      id: cache-snapshot
      with:
        path: |
          snapshot_coins.json
          .first_run_complete
        key: ${{ runner.os }}-snapshot

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run monitoring script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python monitor.py
